on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - uses: nttld/setup-ndk@v1
    with:
      ndk-version: r21d
  - name: Install NDK
    run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
  - name: List SDK
    run: tree ${ANDROID_SDK_ROOT}


